name: BoardPlugin
main: board\Main
version: 1.0.0
api: [3.0.0, 3.0.0-alpha4]
author: wakame0731
description: 掲示板プラグイン

commands:
      sign:
        description: set sign
        usage: "Usage:/sign <message(42文字まで)>" 
        permission: command.board.all
      board:
        description: set message on board
        usage: "Usage:/board <掲示板名> <message(42文字まで)>"
        permission: command.board.all
      regist:
        description: register board
        usage: "Usage:Regist"
        permission: command.board.op
permissions:
  command.board.plugin : 
    description: ""
    default: true
  command.board.op:
    description: ""
    default: true